apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdc
  template:
    metadata:
      labels:
        app: pdc
    spec:
      containers:
      - image: okteto.dev/pdc:latest
        name: pdc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a85693f4-a499-41ca-96e6-72a27779895c"
        - name: Vless_Path
          value: "/fgnjfudbshdgyjytjddju"
        - name: Vmess_UUID
          value: "a85693f4-a499-41ca-96e6-72a27779895c"
        - name: Vmess_Path
          value: "/unetyrtudntjrgyuitstrhsb"
        - name: Share_Path
          value: "/v2lignk"
